### ISSUE TITLE
Documentation is not clear how to Crop using X-Axis and Y-Axis

### ISSUE THREAD

**Issue by sahanDissanayake** [avenirer/CodeIgniter-Image-nation#1]
Hi,

How can I use the X Y axis when I cropping an image @avenirer  ?

**Comment by avenirer** [comment]
Well... By saying that the cropping and/or resize is automatic I mean... "automatic". So you can't set an x or y value. You can only set the configuration item $config[‘default_style’] = array(‘vertical’=>’center’,’horizontal’=>’center’); which will let the library know what should it take into consideration when a crop is done. For vertical you can set top, middle or bottom. For horizontal you can set left, center, right.
